server:
  port: 9001

spring:
  application:
    name: remote-label-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'