server:
  port: 9003

spring:
  application:
    name: remote-label-manage
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/remote_label_manage?autoReconnect=true
    username: root
    password: 123456

#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'