server:
  port: 9003

spring:
  application:
    name: remote-label-manage
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'