server:
  port: 9000

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      nacos:
        discovery:
          server-addr: localhost:8848
      routes:
        - id: remote-label-user # ???id,???????????,???????
          #????????????
          uri: http://localhost:9001
          predicates:
            - Path=/ # ?????????????
#       - id: payment_route2
#         uri: http://localhost:8001
#         predicates:
#           - Path=/payment/lb/** #??,??????????


